# Generated by Django 3.1.2 on 2020-10-19 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='published',
        ),
    ]
